[package]
name = "conformance-tests-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
conformance-tests = { path = "crates/conformance-tests" }
flate2 = { workspace = true }
regex = { workspace = true }
tempfile = "3.3"
tar = { workspace = true }

[workspace]
members = ["components/*", "crates/*"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
flate2 = "1.0"
helper = { path = "crates/helper" }
regex = "1.10"
reqwest = "0.12"
tar = "0.4.45"
wit-bindgen = "0.60"
