[package]
name = "postgres-test-component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
helper = { workspace = true }
rust_decimal = "1.37"
serde_json = "1.0"
wit-bindgen = { workspace = true }
