[package]
name = "outbound-mqtt-test-component"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
helper = { workspace = true }
wit-bindgen = { workspace = true }
