[package]
name = "request-shape"
authors = ["Ryan Levick <me@ryanlevick.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { workspace = true }
anyhow = { workspace = true }
