[package]
name = "conformance-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
flate2 = { workspace = true }
json5 = "1"
libtest-mimic = "0.8"
reqwest = { workspace = true, features = ["blocking"] }
serde = { version = "1.0", features = ["derive"] }
tar = { workspace = true }
test-environment = { path = "../test-environment" }
